apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-deployment
spec:
  selector:
    matchLabels:
      app: ambassador
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: ambassador
    spec:
      containers:
        - image: nginx
          name: ambassador
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
      volumes:
        - name: config-volume
          configMap:
            name: ambassador-config
