apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
        - name: web-depoyment
          image: mcr.microsoft.com/azuredocs/aci-helloworld
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
