kind: Service
apiVersion: v1
metadata:
  name: dictionary-server-service
spec:
  selector:
    app: dictionary-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
